# Generated by Django 4.0.6 on 2022-07-31 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=50, null=True)),
                ('urgency', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50, null=True)),
                ('status_date', models.DateField(null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numb', models.CharField(default='V2743', max_length=50)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(default='', max_length=200)),
                ('date_created', models.DateField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50, null=True)),
                ('urgency', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50, null=True)),
                ('status_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
