# Generated by Django 4.0.6 on 2022-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numb',
            field=models.CharField(default='H5550', max_length=50),
        ),
    ]
