# Generated by Django 4.0.6 on 2022-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_user_ticket_creator_alter_ticket_numb_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(choices=[('tomas-reves', 'tomas-reves'), ('admin-2', 'admin-2'), ('mantas.petraitis', 'mantas.petraitis'), ('jonas.kazlauskas', 'jonas.kazlauskas'), ('petras.nauseda', 'petras.nauseda'), ('justina.zukauskaite', 'justina.zukauskaite'), ('simona.paulauskaite', 'simona.paulauskaite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_ticket_creator',
            field=models.CharField(choices=[('tomas-reves', 'tomas-reves'), ('vardenis.pavardenis', 'vardenis.pavardenis'), ('admin-2', 'admin-2'), ('mantas.petraitis', 'mantas.petraitis'), ('jonas.kazlauskas', 'jonas.kazlauskas'), ('petras.nauseda', 'petras.nauseda'), ('justina.zukauskaite', 'justina.zukauskaite'), ('simona.paulauskaite', 'simona.paulauskaite'), ('jonas.paulauskas', 'jonas.paulauskas'), ('dominyka.morkunaite', 'dominyka.morkunaite'), ('mantas.stonkus', 'mantas.stonkus'), ('martynas.bigas', 'martynas.bigas'), ('justinas.pocius', 'justinas.pocius')], max_length=50, null=True),
        ),
    ]
