# Generated by Django 4.0.6 on 2022-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_archive_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_ticket_creator',
            field=models.CharField(choices=[('tomas-reves', 'tomas-reves'), ('vardenis.pavardenis', 'vardenis.pavardenis'), ('admin-2', 'admin-2'), ('mantas.petraitis', 'mantas.petraitis'), ('jonas.kazlauskas', 'jonas.kazlauskas'), ('petras.nauseda', 'petras.nauseda'), ('justina.zukauskaite', 'justina.zukauskaite'), ('simona.paulauskaite', 'simona.paulauskaite'), ('jonas.paulauskas', 'jonas.paulauskas'), ('dominyka.morkunaite', 'dominyka.morkunaite'), ('mantas.stonkus', 'mantas.stonkus'), ('martynas.bigas', 'martynas.bigas'), ('justinas.pocius', 'justinas.pocius'), ('petras.petraitis', 'petras.petraitis')], max_length=50, null=True),
        ),
    ]
