# Generated by Django 4.0.6 on 2022-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_user_ticket_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(choices=[('tomas-reves', 'tomas-reves'), ('admin-2', 'admin-2'), ('mantas.petraitis', 'mantas.petraitis'), ('jonas.kazlauskas', 'jonas.kazlauskas'), ('petras.nauseda', 'petras.nauseda'), ('justina.zukauskaite', 'justina.zukauskaite'), ('simona.paulauskaite', 'simona.paulauskaite'), ('justinas.pocius', 'justinas.pocius')], max_length=50),
        ),
    ]
