# Generated by Django 4.0.6 on 2022-11-07 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=users.models.employee_id_generator, max_length=50)),
                ('position', models.CharField(blank=True, choices=[('Specialist', 'Specialist'), ('Sr Specialist', 'Sr Specialist'), ('Analyst', 'Analyst'), ('Sr Analyst', 'Sr Analyst'), ('Manager', 'Manager')], max_length=100, null=True)),
                ('departament', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources')], max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users/templates/profile_imgs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
