# Generated by Django 4.0.6 on 2022-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users\\templates\\profile_imgs\\default.jpg', null=True, upload_to='users\\templates\\profile_imgs'),
        ),
    ]
