# Generated by Django 4.0.6 on 2022-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_departament_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
