# Generated by Django 4.0.6 on 2022-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_department_department_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Human Resourses', 'Human Resourses'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Support', 'Support'), ('Finance', 'Finance'), ('Management', 'Management'), ('Test', 'Test'), ('Test2', 'Test2'), ('Test3', 'Test3')], max_length=100, null=True),
        ),
    ]
